### ISSUE TITLE
Failed to fetch mempool content : Method not found

### ISSUE THREAD

**Issue by sergicontre** [itzmeanjan/harmony#10]
Is it possible to connect harmony with a node openethereum (parity)?

**Comment by itzmeanjan** [comment]
No, it's not yet.

**Comment by itzmeanjan** [comment]
Hello @sergicontre , I'm planning to add Parity `tx_queue` support after #11 is done

**Comment by sergicontre** [comment]
Thank you!!

**Comment by sergicontre** [comment]
Hi @itzmeanjan , 

has support for parity / openethereum finally been included?

**Comment by maurodelazeri** [comment]
@sergicontre openethereum is at the end of life... it is not going to be continued after EIP1559... [erigon](https://github.com/ledgerwatch/erigon) is taking over and that is a fork of geth

**Comment by sergicontre** [comment]
It makes a lot of sense. Thanks!
