### ISSUE TITLE
Failed to acquire resource(s) : tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by reshmem** [itzmeanjan/harmony#22]
------------------------- RUN ------------------------------
user@fly9:~/Source/harmony$ ./harmony 
2021/08/22 17:54:57 [😌] Harmony - Reducing Chaos in MemPool
2021/08/22 17:54:57 [❗️] Failed to acquire resource(s) : tls: first record does not look like a TLS handshake

------------------------- ENV FILE -------------------------
user@fly9:~/Source/harmony$ cat .env 
RPCUrl=https://localhost:8545
WSUrl=wss://localhost:8546
MemPoolPollingPeriod=1000
PendingPoolSize=4096
QueuedPoolSize=4096
PendingTxEntryTopic=pending_pool_entry
PendingTxExitTopic=pending_pool_exit
QueuedTxEntryTopic=queued_pool_entry
QueuedTxExitTopic=queued_pool_exit
ConcurrencyFactor=10
Port=7000
Pub0SubHost=127.0.0.1
Pub0SubPort=13000

--------------------------------- NETSTAT PORT CHECK OF GETH -------------------------
user@fly9:~/Source/harmony$ netstat -nalptl | grep geth | grep 85 | grep -v EST
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      2264523/geth        
tcp        0      0 127.0.0.1:8546          0.0.0.0:*               LISTEN      2264523/geth        

--------------------------------- GETH VERSION -------------------------------------------
user@fly9:~$ geth version
Geth
Version: 1.10.6-stable
Git Commit: 576681f29b895dd39e559b7ba17fcd89b42e4833
Architecture: amd64
Go Version: go1.16.4
Operating System: linux

--------------------------------- HARMONY VERSION -------------------------------------
commit 4572d3712321cdaeb20e3313067f71ad3b3268dd (HEAD -> main, tag: v0.9.5, origin/main, origin/HEAD)

--------------------------------- WIRESHARK SCEENSHOT if it helps ----------------------
![image](https://user-images.githubusercontent.com/3090674/130359806-83b77436-051d-44a0-b6cc-8dfb28bd4309.png)

**Comment by itzmeanjan** [comment]
Are you sure 👇 should be what it is ?

```bash
RPCUrl=https://localhost:8545
WSUrl=wss://localhost:8546
```

I think it should be

```bash
RPCUrl=http://localhost:8545
WSUrl=ws://localhost:8546
```
