### ISSUE TITLE
Failed to fetch mempool content : the method txpool_content does not exist/is not available

### ISSUE THREAD

**Issue by DarkFunct** [itzmeanjan/harmony#23]
2022/02/13 07:27:21 [😌] Harmony - Reducing Chaos in MemPool
2022/02/13 07:27:21 [❃] Running in solo mode

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.2.0
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:7000
2022/02/13 07:27:21 [❗️] Failed to fetch mempool content : the method txpool_content does not exist/is not available
2022/02/13 07:27:21 ❗️ Block header subscription failed
2022/02/13 07:27:21
[✅] Gracefully shut down `harmony` after 8.188836ms

can u help me?

**Comment by itzmeanjan** [comment]
The RPC node you're connected to doesn't expose/ implement https://geth.ethereum.org/docs/rpc/ns-txpool#txpool_content method, which is required for `harmony` to work.
