### ISSUE TITLE
 Failed to publish tx ... pool : connection already teared down

### ISSUE THREAD

**Issue by mgpai22** [itzmeanjan/harmony#25]
Got this error in the console while running the program. The subscription feature also does not work, it just endlessly loads. I assume these issues are connected. The pub0 has been configured with default settings and is running in the background. The log starts by saying listening on xyz. Then it constantly switches from connected to disconnected

![harmony console](https://user-images.githubusercontent.com/64056966/162115941-48f0487d-2813-453c-aa9b-334ceb6bddfc.png)

![pub0 logs](https://user-images.githubusercontent.com/64056966/162116215-bc6dd618-382e-4184-8ddf-24f3aac967f5.jpg)
.

**Comment by itzmeanjan** [comment]
Looks like this is an issue of `pub0sub` dependency, not behaving as it should be.

**Comment by itzmeanjan** [comment]
Probably you can try with https://github.com/itzmeanjan/harmony/releases/tag/v0.9.2, which uses Redis.

**Comment by mgpai22** [comment]
It nearly worked! I now get a block fetching error. Could this be due to the node itself?
![fetch error](https://user-images.githubusercontent.com/64056966/162202182-ec4f2005-2144-4b14-8287-e62f7d0eab4d.jpg)

**Comment by mgpai22** [comment]
It does not appear to be a node problem unless there is a flag I am not running geth with.

**Comment by itzmeanjan** [comment]
Though as far as I understand it looks like Ethereum Node's RPC related issue.

**Comment by itzmeanjan** [comment]
This happens here https://github.com/itzmeanjan/harmony/blob/4572d3712321cdaeb20e3313067f71ad3b3268dd/app/listen/header.go#L110-L116, I wonder is the blockchain mining blocks ?

**Comment by mgpai22** [comment]
Depends on how mining is defined. I am running harmony on goerli testnet.

**Comment by mgpai22** [comment]
Used the most recent version with Ropsten (POW testnet) and it worked flawlessly! 

Is it possible to modify harmony so it can be used with other EVM clones such as BSC?

Thanks!

**Comment by itzmeanjan** [comment]
I myself used `harmony` with Polygon PoS chain. As long as BSC nodes implement the `txpool` RPC methods which `harmony` uses, it should work.

**Comment by mgpai22** [comment]
Interesting. It is weird that this did not work with the goerli geth node.

**Comment by itzmeanjan** [comment]
To be more specific https://geth.ethereum.org/docs/rpc/ns-txpool is what exactly is required by `harmony`.

**Comment by Heinux** [comment]
I think you should update go eth to v1.10.17

**Comment by itzmeanjan** [comment]
> I think you should update go eth to v1.10.17

You're correct. Similar issue was present in `ette`, which was detected & fixed https://github.com/itzmeanjan/ette/pull/69

**Comment by itzmeanjan** [comment]
If one has time, feel free to send PR or I'll raise one sometime this week.
